apps/web/models.py
from apps.app import db

relations = db.Table(
    "relations",
    db.Column("article_id", db.Integer, db.ForeignKey("articles._id")),
    db.Column("tag_id", db.Integer, db.ForeignKey("tags._id")),
)


class Article(db.Model):
    __tablename__ = "articles"

    _id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, index=True)
    title = db.Column(db.String, index=True)
    tags = db.relationship(
        "Tag",
        secondary=relations,
        lazy="subquery",
        backref=db.backref("article", lazy="dynamic"),
    )
    pro_link = db.Column(db.String)
    content = db.Column(db.Text)

    def __init__(self, number, title, pro_link, content):
        self.number = number
        self.title = title
        self.pro_link = pro_link
        self.content = content


class Tag(db.Model):
    __tablename__ = "tags"
    _id = db.Column(db.Integer, primary_key=True)
    tag = db.Column(db.String, nullable=False)

    def __init__(self, tag):
        self.tag = tag

apps/web/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ArticleForm(FlaskForm):
    number = IntegerField(
        label="Problem No.", validators=[DataRequired("Requires the problem number")]
    )
    title = StringField(
        label="Problem title",
        validators=[DataRequired("Please provide the problem's title")],
    )
    tag = StringField(
        validators=[
            DataRequired(
                "Please provide at least a tag and separate multiple tag with '/'"
            )
        ]
    )
    pro_link = StringField(
        label="Link to the problem",
        validators=[DataRequired("Please paste the link for the article")],
    )

    content = TextAreaField(
        label="Content", validators=[DataRequired("Please provide the content")]
    )

    submit = SubmitField("Add")

apps/web/__init__.py
import apps.web.models

apps/web/views.py
from pathlib import Path

import markdown
import markdown.extensions.fenced_code
from flask import Blueprint, redirect, render_template, url_for

from apps.app import db
from apps.web.forms import ArticleForm
from apps.web.models import Article, Tag
from apps.web.utils import add_toc

article_basedir = Path(__file__).parent.parent.parent


web = Blueprint(
    "web",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/static",
)


def add_article(article, tags):
    # Remove the tag with no article linked to it
    for tag in article.tags:
        if tag.article.count() == 1:
            db.session.delete(tag)

    # Clear the original tags and link the new tags to it
    article.tags.clear()
    for tag in tags.data.split("/"):
        new_tag = Tag.query.filter_by(tag=tag).first()
        if new_tag is None:
            new_tag = Tag(tag)
        article.tags.append(new_tag)
    db.session.add(article)
    db.session.commit()


@web.route("/")
def index():
    articles = Article.query.order_by(Article.number).all()
    return render_template("index.html", articles=articles)


@web.route("/article/new", methods=["GET", "POST"])
def create_article():
    form = ArticleForm()

    if form.validate_on_submit():
        article = Article(
            number=form.number.data,
            title=form.title.data,
            pro_link=form.pro_link.data,
            content=form.content.data,
        )

        add_article(article, form.tag)

        return redirect(url_for("web.index"))

    return render_template("add_article.html", form=form)


@web.route("/article/<number>")
def read_article(number):
    mkd_text = markdown.markdown(
        add_toc(Article.query.filter_by(number=number).first().content),
        extensions=["fenced_code", "mdx_math", "codehilite", "toc"],
        extension_configs={
            "mdx_math": {
                "enable_dollar_delimiter": True,
            },
            "toc": {"anchorlink": "icon"},
        },
    )

    return render_template(
        "markdown.html",
        mkd_text=mkd_text,
    )


@web.route("/article/edit/<number>", methods=["GET", "POST"])
def edit_article(number):
    article = Article.query.filter_by(number=number).first()
    form = ArticleForm()

    if form.validate_on_submit():
        article.number = form.number.data
        article.title = form.title.data
        article.pro_link = form.pro_link.data
        article.content = form.content.data
        add_article(article, form.tag)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for("web.index"))

    # Prevent from overwritten after click the submit button
    form.tag.data = "/".join([tag.tag for tag in article.tags])
    form.content.data = article.content
    return render_template("edit.html", form=form, article=article)


@web.route("/tag/<tag>")
def get_tag(tag):
    articles = (
        Tag.query.filter_by(tag=tag).first().article.order_by(Article.number).all()
    )

    return render_template("index.html", articles=articles)

apps/web/templates/add_article.html
{% extends "base.html" %} {% block title %}Add an article{% endblock %} {% block
content %} {% block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('web.static', filename='form.css') }}"
/>
<script
  src="https://kit.fontawesome.com/8f31de1937.js"
  crossorigin="anonymous"
></script>
{% endblock %}

<h2>Add new article</h2>
<form
  action="{{ url_for('web.create_article') }}"
  method="POST"
  novalidate="novalidate"
>
  {{ form.csrf_token }}
  <p>{{ form.number.label }}</p>
  <p>{{ form.number(placeholder="Number only", class_="text-input") }}</p>
  {% for error in form.number.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.title.label }}</p>
  <p>{{ form.title(placeholder="", class_="text-input") }}</p>
  {% for error in form.title.errors %}
  <p class="error-msg">
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.tag.label }}</p>
  <p>
    {{ form.tag(placeholder="Use '/' to separate different tags",
    class_="text-input") }}
  </p>
  {% for error in form.tag.errors %}
  <p class="error-msg">
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.pro_link.label }}</p>
  <p>{{ form.pro_link(class_="text-input") }}</p>
  {% for error in form.pro_link.errors %}
  <p class="error-msg">
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.content.label }}</p>
  <p>{{ form.content(rows='100') }}</p>
  {% for error in form.content.errors %}
  <p class="error-msg">
    <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('web.static', filename='style.css') }}"
    />
    {% block extra_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        config: ["MMLorHTML.js"],
        jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
        extensions: ["MathMenu.js", "MathZoom.js"]
      });
    </script>
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML"
    ></script>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

apps/web/templates/edit.html
{% extends "base.html" %} {% block title %}Edit an article{% endblock %} {%
block content %} {% block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('web.static', filename='form.css') }}"
/>
<script
  src="https://kit.fontawesome.com/8f31de1937.js"
  crossorigin="anonymous"
></script>
{% endblock %}

<h2>Edit the article</h2>
<form
  action="{{ url_for('web.edit_article', number=article.number) }}"
  method="POST"
  novalidate="novalidate"
>
  {{ form.csrf_token }}
  <p>{{ form.number.label }}</p>
  <p>
    {{ form.number(placeholder="Number only", value=article.number,
    class_="text-input") }}
  </p>
  {% for error in form.number.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.title.label }}</p>
  <p>
    {{ form.title(placeholder="", value=article.title, class_="text-input") }}
  </p>
  {% for error in form.title.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.tag.label }}</p>
  <p>
    {{ form.tag(placeholder="Use '/' to separate different tags",
    class_="text-input") }}
  </p>
  {% for error in form.tag.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.pro_link.label }}</p>
  <p>{{ form.pro_link(value=article.pro_link, class_="text-input") }}</p>
  {% for error in form.pro_link.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.content.label }}</p>
  <p>{{ form.content(rows='100') }}</p>
  {% for error in form.content.errors %}
  <p class="error-msg">
    <i class="fas fa-triangle-exclamation"></i>&nbsp;{{ error }}
  </p>
  {% endfor %}
  <p>{{ form.submit(value="Update") }}</p>
</form>
{% endblock %}

apps/web/templates/index.html
{% extends "base.html" %} {% block title %}Home Page - List of
Problems{%endblock %} {% block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('web.static',
filename='table.css') }}"
/>
{% endblock %} {% block content %}
<a href="{{ url_for('web.create_article')}}">Add article</a>
<h2>Articles List</h2>
<table>
  <thead>
    <tr>
      <th>NO.</th>
      <th>Title</th>
      <th>Explanation</th>
      <th>Tag</th>
      <th>Leetcode</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <td class="center-col">{{ article.number }}</td>
      <td class="center-col">{{ article.title }}</td>
      <td class="center-col">
        <a href="{{ url_for('web.read_article', number=article.number) }}"
          >solution</a
        >
      </td>
      <td class="center-col">
        <div>
          {% for tag in article.tags %}<a
            href="{{ url_for('web.get_tag', tag=tag.tag) }}"
            class="post-tag"
            >#{{ tag.tag }}</a
          >{% endfor %}
        </div>
      </td>
      <td class="center-col">
        <a
          href="https://leetcode.com/problems/{{ article.pro_link }}"
          target="_blank"
          rel="noopener noreferrer"
          >Link</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

apps/web/templates/markdown.html
{% extends "base.html" %} {% block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('web.static', filename='codehilite.css') }}"
/>
{% endblock %} {% block title %}Solution{% endblock %} {% block content %}
<style>
  .markdown-body {
    box-sizing: border-box;
    min-width: 200px;
    max-width: 980px;
    margin: 0 auto;
    padding: 45px;
  }

  @media (max-width: 767px) {
    .markdown-body {
      padding: 15px;
    }
  }
</style>
<article class="markdown-body">{{ mkd_text|safe }}</article>
{% endblock %}